version: "2"

services:
  hash-translator:
    build:
      context: hashtranslator-service/
    restart: on-failure
    environment:
      EMAIL: fromthedeepsize@gmail.com
      HASH_TYPE: md5
      SECRET_KEY: b66ed0a38d36f3c3
    expose:
      - "8082"
    depends_on:
      - mongo
  authorization-service:
    build:
      context: authorization-service/
    restart: on-failure
    environment:
      TRANSLATION_SERVICE_URL: http://hash-translator:8082
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  postgres: {}
  mongo: {}